### ISSUE TITLE
Support stack grouping in flamegraph

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode-js-profile-visualizer#11]
This is super useful if you only want to know what function calls/call stacks take a lot of time, but don't care about the order functions are called in.

See e.g. the "left heavy" mode in https://www.speedscope.app/ for how this would look.

**Comment by connor4312** [comment]
This is now done

![](https://memes.peet.io/img/20-09-664599cc-88ce-4f88-9a8c-2f901a6a08fb.png)

It can be toggled by clickong in that placeholder icon beside the flamegraph. I'll request that we get a better icon for it.

**Comment by connor4312** [comment]
Moving this issue to js-debug so that it gets picked up in our endgame
