### ISSUE TITLE
CPU profile annotations show doubled values

### ISSUE THREAD

**Issue by anotherandi** [microsoft/vscode-js-profile-visualizer#135]
The values in the source annotation show exactly the doubled values from the table view.
![annotation](https://user-images.githubusercontent.com/48909831/211221747-a971ea8d-ef5c-44ac-a6f6-b668f7210c65.png)
The values in the table view are plausible. The wrong values in the annotations are doubled for both the Self value and the Total value.

![table](https://user-images.githubusercontent.com/48909831/211221751-fde9015c-f759-4d6a-8135-6dd77857d3fb.png)

**Comment by connor4312** [comment]
Fixed in the latest VS Code Insiders
