### ISSUE TITLE
Async functions not getting included?

### ISSUE THREAD

**Issue by Rich-MSR** [microsoft/vscode-js-profile-visualizer#15]
It seems that the profiler does not include timings for async functions: the execution time is simply attributed to the caller of the async function.  This is different from what the [ms-vscode.js-debug 1.47.3] debugger does, where I can see the async methods in the call stack (after the "_async function_" break.

Suggestion: Can we have the profiler report the async methods as the debugger does? As it stands, it's hard to profile async code.

_[I'm developing in TypeScript 3.9.6]_

Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Unfortunately this is a limitation with how the Chrome profiler works. Essentially, it just takes a snapshot of the current (synchronous) call stack every 1ms, and dumps that out to us to visualize. Async functions are inscrutable in this stack.
