### ISSUE TITLE
Opening multiple large .cpuprofile files seems to crash the webview

### ISSUE THREAD

**Issue by TwitchBronBron** [microsoft/vscode-js-profile-visualizer#152]
I have some fairly large cpuprofile files. Opening the first one works, but when I go to open the second one, it goes to a blank screen. Is there some memory or CPU limitation in the webviews that's causing this? 
 
![profile](https://github.com/microsoft/vscode-js-profile-visualizer/assets/2544493/a4bf9fb9-b82e-4ec2-b846-0f8b686c9b1f)

The vscode devtools seem to disconnect the moment the webview goes to the grey screen.
![profile2](https://github.com/microsoft/vscode-js-profile-visualizer/assets/2544493/2bfbeba6-0bdc-437c-83bb-feae2ce7db5c)

- File 1: [1698236592187-bsc-profile-1698236556798.cpuprofile](https://github.com/microsoft/vscode-js-profile-visualizer/files/13166492/1698236592187-bsc-profile-1698236556798.cpuprofile)
- File 2: [1698236759491-bsc-profile-1698236712733.cpuprofile](https://github.com/microsoft/vscode-js-profile-visualizer/files/13166497/1698236759491-bsc-profile-1698236712733.cpuprofile)

**Comment by connor4312** [comment]
Yep, that looks like an OOM crash

**Comment by TwitchBronBron** [comment]
Is there anything that can be done to help mitigate this? Like:
 - storing certain items in a more efficient fashion in memory (like bitmaps instead of integers or strings for certain things)
 - storing the item "server side" (i.e. in the vscode process instead of the webview) and streaming them in chunks to the UI?
 - not rendering all of the results at one time in the UI? (like virtual scrolling).

**Comment by connor4312** [comment]
Fixed in the latest VS Code Insiders
