### ISSUE TITLE
improve array index checks

### ISSUE THREAD

**Issue by marcellourbani** [microsoft/vscode-js-profile-visualizer#159]
By detault typescript doesn't handle array types correctly:

```typescript
const foo:string[]=[]
const bar:string = foo[0] // type checks, but bar is undefined
```
If we enable compiler option **noUncheckedIndexedAccess**, it returns an error:
```
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-js-profile-visualizer/pull/160#issuecomment-1826417231
