### ISSUE TITLE
heap snapshots stuck "building graph layout..."

### ISSUE THREAD

**Issue by IanButterworth** [microsoft/vscode-js-profile-visualizer#175]
If I take a heap snapshot in chrome devtools then open the graph mode in this viewer I just get `building graph layout...` it seems indefinitely. There's no error printed to the `Window` output log

![Screenshot 2024-03-24 at 2 33 51 PM](https://github.com/microsoft/vscode-js-profile-visualizer/assets/1694067/4619e948-adb4-4c4e-9e94-39dd05f04b08)

The same is true of heap snapshots collected in the julia profiler, but that is more experimental, so chrome devtools is probably a better reproducer.

**Comment by IanButterworth** [comment]
I notice that main has unreleased changes and wanted to see if the issue remains on latest main.

I tried to test latest master but couldn't figure out testing the extension.
Issues:
- package.json is missing version and engines fields
- `vsce package` doesn't create a vsix file to load as a local extension

**Comment by connor4312** [comment]
If you run the Toggle Developer Tools command, is there any errors shown there?

Alternatively/preferably, are you able to share a heap snapshot where you see this reproduce?

**Comment by IanButterworth** [comment]
I'm not sure what a chrome heapsnapshot includes, from a security perspective. Would you mind confirming that your own chrome devtools heapsnapshots don't reproduce? If so I can look into sharing one from a blank VM or something.

**Comment by connor4312** [comment]
It includes some stuff about your program structure as well as strings allocated in the heap. If you prefer you can also email it to me at connor@xbox.com rather than posting publicly.

**Comment by IanButterworth** [comment]
Ok. Emailed, thanks

**Comment by connor4312** [comment]
Thanks! This week we're busy getting the next release out, but I'll take a look at this by the end of next week.

**Comment by IanButterworth** [comment]
Ah vscode dev tools does show an error in the console
![Screenshot 2024-03-25 at 12 26 10 PM](https://github.com/microsoft/vscode-js-profile-visualizer/assets/1694067/c74a2f21-2f47-4947-a047-362e6dd404d0)

**Comment by connor4312** [comment]
Circling back here, how are you opening the graph?

The graph as implemented currently only is relevant for selected objects from the table. It doesn't handle opening the entire heap snapshot (something I should make more explicit) because doing so for heaps of any reasonable size results in absolutely terrible performance as the graphs get very massive very quickly 🙂

**Comment by IanButterworth** [comment]
How do you open it for a given object?

**Comment by connor4312** [comment]
By clicking the "graph" button beside an object in memory:

![Image](https://github.com/microsoft/vscode-js-profile-visualizer/assets/2230985/61500173-7c1d-4230-a12d-91e5c52a0a11)

**Comment by IanButterworth** [comment]
I just realized that and it works for the julia heap snapshot! :+1:

![Screenshot 2024-04-04 at 4 30 50 PM](https://github.com/microsoft/vscode-js-profile-visualizer/assets/1694067/603a76cb-6039-4841-825a-727b04287e54)


The behavior I was talking about was from opening via the file open dialog (3rd option here)

![Screenshot 2024-04-04 at 4 32 28 PM](https://github.com/microsoft/vscode-js-profile-visualizer/assets/1694067/1acaec3f-68a8-4646-82e5-cd6ed1670d14)


Perhaps the UI could give a hint to use the icons if the top level load is taking a long time?

**Comment by connor4312** [comment]
I made a PR to remove the flame graph from that switcher https://github.com/microsoft/vscode-js-profile-visualizer/pull/179

**Comment by IanButterworth** [comment]
Is there a place the graph icon is explained? In hindsight it's obvious but it might be worth explaining it in the extension landing page?

**Comment by IanButterworth** [comment]
Looks great, thanks
