### ISSUE TITLE
Very large profile won't open

### ISSUE THREAD

**Issue by TwitchBronBron** [microsoft/vscode-js-profile-visualizer#181]
I'm trying to open a very large `.cpuprofile` file, and it won't open. vscode shows several "this process is not responding" popups, and every time I click "keep waiting", it just spins a bit and shows another popup a moment later. 

![image](https://github.com/microsoft/vscode-js-profile-visualizer/assets/2544493/a0fbf8f5-684b-44d8-b8c1-d6fd47ef5699)

I'm able to successfully open it at https://www.speedscope.app/, so I don't think there's anything wrong with the file itself. 

Here's the profile file if that helps? 
[1712342898999-bsc-profile-1712342878817.cpuprofile](https://github.com/microsoft/vscode-js-profile-visualizer/files/14889598/1712342898999-bsc-profile-1712342878817.cpuprofile)

**Comment by connor4312** [comment]
Thanks for the issue, this will be fixed in tomorrow's [Insiders](https://code.visualstudio.com/insiders/) build.

**Comment by TwitchBronBron** [comment]
I just tested and confirmed that these large profiles work in the latest insiders. Thanks again!
