### ISSUE TITLE
Adding new features

### ISSUE THREAD

**Issue by Luferchoo** [microsoft/vscode-js-profile-visualizer#187]
I want to add another workspace, I develop a new feature that works like another extension, but when I try to add this, I put in the code package.json the scripts needed to compile and watch, It apparently works but when I try to find the command that I put to initialize my workspace it doesn't appear in the vscode command palette. Someone can tell me the way that I can integrate my workspace to run it?

**Comment by connor4312** [comment]
You probably need to update the paths here:

https://github.com/microsoft/vscode-js-profile-visualizer/blob/main/.vscode/launch.json#L26-L29
