### ISSUE TITLE
Performance Graphs not shown after Auto-Attach

### ISSUE THREAD

**Issue by dlschmidt** [microsoft/vscode-js-profile-visualizer#24]
VSCode successfully auto-attaches to processes like ts-node-dev when entered in the terminal. But when I try to display the performance graphs, none is shown. I guess maybe only one additional event handler is missing.

![image](https://user-images.githubusercontent.com/20640295/95664838-ab572580-0b4b-11eb-8022-137eef9bcfd4.png)

**Comment by connor4312** [comment]
The graph is shown for the currently selected debug session -- which session do you have selected in the sidebar?

**Comment by dlschmidt** [comment]
When using Auto-Attach, "No configrations" is selected in the sidebar. Apparently only a "temporary" configuration exists for that debug session.
