### ISSUE TITLE
Heap used reports "Resident Set Size" instead of "Used Heap" size when profiling Node.js

### ISSUE THREAD

**Issue by timneutkens** [microsoft/vscode-js-profile-visualizer#62]
Hey 👋  We've recently been using this vscode extension to capture and investigate performance profiles while working on Next.js, this is mostly focused on CPU profiling. Today I was having a look at some memory leak reports and realized memory usage was growing uncontrollably up to 1GB in the debugger chart while the Chrome devtools debugger kept saying only 54MB was allocated. 

When looking at `process.memoryUsage()` I realized that the extension reports the `process.memoryUsage().rss` instead of `process.memoryUsage().heapUsed` which Chrome reports. Below the chart it is labeled as "Heap used" though. 

My main question is if this is a mistake or intentional? Happy to send a PR to update the label or measurement.

(just for my own future reference) In looking at the issue I found this article that goes in-depth on the differences between the metrics reported https://www.dynatrace.com/news/blog/understanding-garbage-collection-and-hunting-memory-leaks-in-node-js/

**Comment by connor4312** [comment]
A PR would be welcome 🙂

**Comment by timneutkens** [comment]
@connor4312 would you like to be reported `rss` or `heapUsed` to be reported? It seems that Chrome reports `heapUsed` when looking at the memory as that is the actual usage excluding the code loaded.

**Comment by connor4312** [comment]
Yes, a change to `heapUsed` would be good. Thanks for linking the article, it's quite helpful, especially this diagram:

![image](https://user-images.githubusercontent.com/2230985/151212687-585075d1-9945-4260-8352-7e556d4de002.png)

**Comment by timneutkens** [comment]
Opened a PR with the changes discussed in this issue: #63 🎉

**Comment by timneutkens** [comment]
Thanks for landing this @connor4312 🎉
