### ISSUE TITLE
Release missing for `v1.0.4`

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode-js-profile-visualizer#85]
Hi there 👋!

It looks like the release for version `1.0.4` is missing in GitHub Releases, although there is a tag for it (https://github.com/microsoft/vscode-js-profile-visualizer/releases/tag/v1.0.4). Maybe this is intentional, but wanted to bring this to your attention 😊.

**Comment by filiptronicek** [comment]
cc @connor4312 @joaomoreno

**Comment by connor4312** [comment]
Added
