### ISSUE TITLE
Update marketplace description

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-js-profile-visualizer#9]
The description for the extension at https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame is kind of confusing for end users :)

We plan to ship a new Julia extension version soon that will write .cpuprofile files. At that point the shipping version of VS Code handles those file types, and if a user clicks on the flame graph icon in the custom editor that opens the extension page that has this incomplete description.

Could you maybe publish a new version of the extension that just has a more meaningful homepage on the marketplace? Doesn't have to be long, just some text a la "This adds flamegraph support for .cpuprofile" files would be fantastic already.

**Comment by davidanthoff** [comment]
Excellent, thanks!

**Comment by connor4312** [comment]
no problem, will publish in a little bit
